FROM golang:1.25-alpine AS builder

WORKDIR /app/agent

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /agent ./cmd/agent


FROM alpine:3.19
WORKDIR /app

COPY --from=builder /agent ./agent
COPY configs/agent_config.yaml ./configs/agent_config.yaml

CMD ["./agent"]
