FROM golang:1.25-alpine AS builder

WORKDIR /app/collector

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /collector ./cmd/collector


FROM alpine:3.19
WORKDIR /app

COPY --from=builder /collector ./collector
COPY configs/collector_config.yaml ./configs/collector_config.yaml
COPY static/ ./static/

EXPOSE 8080

CMD ["./collector"]
